version: "3.8"
services: 
  postgres: 
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=b_micro
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment: 
      - DB_SOURCE=postgresql://root:123456@postgres:5432/b_micro?sslmode=disable
    depends_on: 
      - postgres
    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]


